### ISSUE TITLE
tests: add tests for kubernetes upgrades

### ISSUE THREAD

**Issue by wozniakjan** [kubermatic/kubevirt-csi-driver-operator#13]
Document a way how to test this driver after kubernetes upgrades for both host and tenant clusters. If possible, consider implementing automated e2e tests.

**Comment by wozniakjan** [comment]
here is a draft of a potential workflow:
* use `kubermatic-installer local kind`, it's possible to control the master/seed version with nodeimage in kind-config
```
image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
```
* configure update versions in `KubermaticConfiguration` CR
```
    versions:
      default: 1.27.3
      updates:
      - from: 1.27.*
        to: 1.28.1
      versions:
      - 1.27.3
      - 1.28.1
```
* provision PVs in the kubevirt user-cluster and observe logs in user-cluster `kubevirt-csi-driver/kubevirt-csi-driver-operator`
